name: SimpleAuthMe
main: com.simpleauth.Plugin
version: 0.2
api-version: 1.16
author: ["KiroHoang"]
description: Init Account in server
commands:
  authme: # usage: /authme
    description: show available commands
  register: # usage: /register <password>
    description: register account
    aliases: [r]
  login: # usage: /login <password>
    description: login account
    aliases: [l]
  addemail: # usage: /addemail <email>
    description: Add an email address