name: simpleauthme
main: com.simpleauth.Plugin
version: 0.1
api-version: 1.15
author: ["KiroHoang"]
description: Init Account in server
commands:
  register:
    description: register account
    usage: /register <password>
    aliases: [r]
  login:
    desription: login account
    usage: /login <password>
    aliases: [l]