name: simpleauthme
main: com.simpleauth.Plugin
version: 0.2
api-version: 1.16
author: ["KiroHoang"]
description: Init Account in server
commands:
  authme:
    description: show available commands
    usage: /authme
  register:
    description: register account
    usage: /register <password>
    aliases: [r]
  login:
    description: login account
    usage: /login <password>
    aliases: [l]
  addemail:
    description: Add an email address
    usage: /addemail <email>
    
